#!/bin/bash

## Removendo travas eventuais no apt
sudo rm /var/lib/dpkg/lock-fontend && sudo rm /var/cache/apt/archives/lock

## Indo para home
cd $HOME

## Linguagens
sudo apt install julia

## Vim
sudo apt install vim 

## Movendo pastas do repo
mkdir Programas
fightcade="/DebianPosInstall/figthcade "
if [ ! -d fightcade ]; then
	mv fightcade Programas
fi

## Criando Lista de Favoritos do Chrome
FAV=(
	LEARN 									- https://www.youtube.com/playlist?list=PLGNztVHyC5OpR_ZOAvUcN4kROML6sVPbd
	SergioAlmeidaCiprianoJr - https://github.com/SergioAlmeidaCiprianoJr
	CD-MOJ 									- https://moj.naquadah.com.br/cgi-bin/index.sh
	Telegram								- https://web.telegram.org
	Wpp Web									- https://web.whatsapp.com/
	Matricula Web 					- https://matriculaweb.unb.br/graduacao/sec/login.aspx
	Apender UnB							- https://aprender.ead.unb.br/
	MIT open course ware		- https://ocw.mit.edu/index.htm
	IRC											- https://irc.lappis.rocks/
	Livro de Shell					- https://bash.cyberciti.biz/guide/Main_Page
	URI 										- https://www.urionlinejudge.com.br/judge/pt/
	CodeForces							- https://codeforces.com/
)
touch ListaFavoChrome
for favorito in ${FAV[*]}; do
	echo "favorito" >> ListaFavoChrome
done

## Criando Lista de Extensões do Chrome
EXT=(
	Dark Reader 						- https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=pt-BR
	Evernote Clipper 				- https://evernote.com/intl/pt-br/features/webclipper
	Zenhub 									- https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd?hl=pt-BR
)
touch ListaExtChrome
for extensao in ${EXT[*]}; do
	echo "extensao" >> ListaExtChrome
done

## Git
mkdir UnB && cd UnB
git clone https://github.com/SergioAlmeidaCiprianoJr/Practice.git
git clone https://github.com/edsomjr/TEP.git

## Snap install
snap install code --classic
snap install sublime-text
snap install spotify

## Finalização, atualização e limpeza
sudo apt update && sudo apt dist-upgrade -y
flatpak update
sudo apt autoclean
sudo apt autoremove -y
