#!/bin/bash

# eq = equal to
# ne = not equal to
# le = less than and equal to
# lt = less than
# gt = greater than
# ge = greater than and equal to

####################################

read -p "What is your name? " name

echo "Hello $name"

read -p "How old are you? " age

if [ $age -ge 18 ]
then
	echo "You can drive"
elif [ $age -eq 17 ]
then
	echo "You can drive next year"
else
	echo "You can't drive"
fi

####################################

read -p "Enter a number : " num

if (( num == 10 )); then
	echo "Your number equals 10"
fi

if ((num > 10)); then
	echo "It is greater then 10"
fi

if (( !(num % 2) )); then
	echo "It is even"
fi

if (( num > 0 && num < 11)); then
	echo "$num is between 1 and 10"
fi

####################################

touch file && vim file

[ -d dir ] || mkdir dir

