#!/bin/bash

##########################################

OIFS="$IFS"

IFS=","

read -p "Enter 2 numbers to add separated by a comma: " num1 num2

num1=${num1//[[:blank:]]/}
num2=${num2//[[:blank:]]/}

sum=$((num1+num2))

echo "Result $sum"

##########################################

read -p "Enter 2 numbers to sum: " num1 num2

sum=$((num1+num2))

echo "Sum = $sum"

##########################################

read -sp "Enter the secret code: " secret

if [ $secret == "password" ]; then
	echo "Enter"
else 
	echo "Wrong password"
fi

##########################################
